### ISSUE TITLE
各种错！！编译错误！

### ISSUE THREAD

**Issue by oe77** [nealwon/openwrt#1]
$(CP) ./lucsrc/* $(1)/usr/lib/lua/luci/   这里写错了！！

编译完不显示界面！

**Comment by nealwon** [comment]
谢谢！
之前是自己实现的，现在改用luci自己的Makefile了，应该OK了。
安装依赖于vlmcsd，如果/etc/config/vlmcsd文件不存在，界面无法渲染！
